services:
  hand_gesture_unitree:
    build: 
      context: .
      args:
        - internet_card=eth0
    networks:
      rete_cane:
        ipv4_address: "192.168.123.222"

networks:
  rete_cane:
    driver: macvlan
    driver_opts:
      parent: ${NET_IFACE} # nome della tua interfaccia fisica
    ipam:
      config:
        - subnet: "192.168.123.0/24"
          gateway: "192.168.123.1"
